---
box-sizing:
  box-border: border-box
  box-content: content-box
display:
  block: block
  inline-block: inline-block
  inline: inline
  flex: flex
  inline-flex: inline-flex
  table: table
  inline-table: inline-table
  table-caption: table-caption
  table-cell: table-cell
  table-column: table-column
  table-column-group: table-column-group
  table-footer-group: table-footer-group
  table-header-group: table-header-group
  table-row-group: table-row-group
  table-row: table-row
  flow-root: flow-root
  grid: grid
  inline-grid: inline-grid
  contents: contents
  list-item: list-item
  hidden: none
float:
  float-left: left
  float-right: right
  float-none: none
clear:
  clear-left: left
  clear-right: right
  clear-both: both
  clear-none: none
isolate:
  isolate: isolate
  isolation-auto: auto
object-fit:
  object-contain: contain
  object-cover: cover
  object-fill: fill
  object-none: none
  object-scale-down: scale-down
object-position:
  object-bottom: bottom
  object-center: center
  object-left: left
  object-left-bottom: left-bottom
  object-left-top: left-top
  object-right: right
  object-right-bottom: right-bottom
  object-right-top: right-top
  object-top: top
overflow:
  overflow-auto: auto
  overflow-hidden: hidden
  overflow-visible: visible
  overflow-scroll: scroll
overflow-x:
  overflow-x-auto: auto
  overflow-x-hidden: hidden
  overflow-x-visible: visible
  overflow-x-scroll: scroll
overflow-y:
  overflow-y-auto: auto
  overflow-y-hidden: hidden
  overflow-y-visible: visible
  overflow-y-scroll: scroll
overscroll-behavior:
  overscroll-auto: auto
  overscroll-contain: contain
  overscroll-none: none
overscroll-behavior-y:
  overscroll-y-auto: auto
  overscroll-y-contain: contain
  overscroll-y-none: none
overscroll-behavior-x:
  overscroll-x-auto: auto
  overscroll-x-contain: contain
  overscroll-x-none: none
position:
  static: static
  fixed: fixed
  absolute: absolute
  relative: relative
  sticky: sticky
visibility:
  visible: visible
  invisible: hidden
z-index:
  z-0: '0'
  z-10: '10'
  z-20: '20'
  z-30: '30'
  z-40: '40'
  z-50: '50'
  z-auto: auto