---
transform:
  scale-0: scale(0)
  scale-x-0: scaleX(0)
  scale-y-0: scaleY(0)
  scale-25: scale(.25)
  scale-x-25: scaleX(.25)
  scale-y-25: scaleY(.25)
  scale-50: scale(.5)
  scale-x-50: scaleX(.5)
  scale-y-50: scaleY(.5)
  scale-75: scale(.75)
  scale-x-75: scaleX(.75)
  scale-y-75: scaleY(.75)
  scale-90: scale(.9)
  scale-x-90: scaleX(.9)
  scale-y-90: scaleY(.9)
  scale-95: scale(.95)
  scale-x-95: scaleX(.95)
  scale-y-95: scaleY(.95)
  scale-100: scale(1)
  scale-x-100: scaleX(1)
  scale-y-100: scaleY(1)
  scale-105: scale(1.05)
  scale-x-105: scaleX(1.05)
  scale-y-105: scaleY(1.05)
  scale-110: scale(1.10)
  scale-x-110: scaleX(1.10)
  scale-y-110: scaleY(1.10)
  scale-125: scale(1.25)
  scale-x-125: scaleX(1.25)
  scale-y-125: scaleY(1.25)
  scale-150: scale(1.5)
  scale-x-150: scaleX(1.5)
  scale-y-150: scaleY(1.5)
  rotate-0: rotate(0deg)
  rotate-1: rotate(1deg)
  rotate-2: rotate(2deg)
  rotate-3: rotate(3deg)
  rotate-4: rotate(4deg)
  rotate-5: rotate(5deg)
  rotate-6: rotate(6deg)
  rotate-12: rotate(12deg)
  rotate-45: rotate(45deg)
  rotate-90: rotate(90deg)
  rotate-180: rotate(180deg)
  translate-x-0: traslateX(0px)
  translate-y-0: traslateY(0px)
  translate-x-px: traslateX(1px)
  translate-y-px: traslateY(1px)
  translate-x-0\.5: traslateX(0.125rem)
  translate-y-0\.5: traslateY(0.125rem)
  translate-x-1: traslateX(0.25rem)
  translate-y-1: traslateY(0.25rem)
  translate-x-1\.5: traslateX(0.375rem)
  translate-y-1\.5: traslateY(0.375rem)
  translate-x-2: traslateX(0.5rem)
  translate-y-2: traslateY(0.5rem)
  translate-x-2\.5: traslateX(0.625rem)
  translate-y-2\.5: traslateY(0.625rem)
  translate-x-3: traslateX(0.75rem)
  translate-y-3: traslateY(0.75rem)
  translate-x-3\.5: traslateX(0.875rem)
  translate-y-3\.5: traslateY(0.875rem)
  translate-x-4: traslateX(1rem)
  translate-y-4: traslateY(1rem)
  translate-x-5: traslateX(1.25rem)
  translate-y-5: traslateY(1.25rem)
  translate-x-6: traslateX(1.5rem)
  translate-y-6: traslateY(1.5rem)
  translate-x-7: traslateX(1.75rem)
  translate-y-7: traslateY(1.75rem)
  translate-x-8: traslateX(2rem)
  translate-y-8: traslateY(2rem)
  translate-x-9: traslateX(2.25rem)
  translate-y-9: traslateY(2.25rem)
  translate-x-10: traslateX(2.5rem)
  translate-y-10: traslateY(2.5rem)
  translate-x-11: traslateX(2.75rem)
  translate-y-11: traslateY(2.75rem)
  translate-x-12: traslateX(3rem)
  translate-y-12: traslateY(3rem)
  translate-x-14: traslateX(3.5rem)
  translate-y-14: traslateY(3.5rem)
  translate-x-16: traslateX(4rem)
  translate-y-16: traslateY(4rem)  
  translate-x-20: traslateX(5rem)
  translate-y-20: traslateY(5rem)
  translate-x-24: traslateX(6rem)
  translate-y-24: traslateY(6rem)
  translate-x-28: traslateX(7rem)
  translate-y-28: traslateY(7rem)
  translate-x-32: traslateX(8rem)
  translate-y-32: traslateY(8rem)
  translate-x-36: traslateX(9rem)
  translate-y-36: traslateY(9rem)
  translate-x-40: traslateX(10rem)
  translate-y-40: traslateY(10rem)
  translate-x-44: traslateX(11rem)
  translate-y-44: traslateY(11rem)
  translate-x-48: traslateX(12rem)
  translate-y-48: traslateY(12rem)
  translate-x-52: traslateX(13rem)
  translate-y-52: traslateY(13rem)
  translate-x-56: traslateX(14rem)
  translate-y-56: traslateY(14rem)
  translate-x-60: traslateX(15rem)
  translate-y-60: traslateY(15rem)
  translate-x-64: traslateX(16rem)
  translate-y-64: traslateY(16rem)
  translate-x-72: traslateX(18rem)
  translate-y-72: traslateY(18rem)
  translate-x-80: traslateX(20rem)
  translate-y-80: traslateY(20rem)
  translate-x-96: traslateX(24rem)
  translate-y-96: traslateY(24rem)
  translate-x-1\/2: traslateX(50%)
  translate-y-1\/3: traslateY(50%)
  translate-x-2\/3: traslateX(33.333333%)
  translate-y-2\/3: traslateY(33.333333%)
  translate-x-2\/3: traslateX(66.666666%)
  translate-y-2\/3: traslateY(66.666666%)
  translate-x-1\/4: traslateX(25%)
  translate-y-1\/4: traslateY(25%)
  translate-x-3\/4: traslateX(75%)
  translate-y-3\/4: traslateY(75%)
  translate-x-full: traslateX(100%)
  translate-y-full: traslateY(100%)
  skew-x-0: skewX(0deg)
  skew-y-0: skewY(0deg)  
  skew-x-1: skewX(1deg)
  skew-y-1: skewY(1deg)  
  skew-x-2: skewX(2deg)
  skew-y-2: skewY(2deg)  
  skew-x-3: skewX(3deg)
  skew-y-3: skewY(3deg)  
  skew-x-4: skewX(4deg)
  skew-y-4: skewY(4deg)  
  skew-x-5: skewX(5deg)
  skew-y-5: skewY(5deg)  
  skew-x-6: skewX(6deg)
  skew-y-6: skewY(6deg)  
  skew-x-12: skewX(12deg)
  skew-y-12: skewY(12deg)
transform-origin:
  origin-center: center
  origin-top: top
  origin-top-right: top right
  origin-right: right
  origin-bottom-right: bottom right
  origin-bottom: bottom
  origin-bottom-left: botton left
  origin-left: left
  origin-top-left : top left